name: Periodic PHP Deployment #Test2

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GAMEPVTSSH }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.GAMEPVTSSH }}  # Or use private key authentication
          port: ${{ secrets.DEPLOY_PORT }}  # Specify the SSH port
          script: |
            sudo su
            sudo supervisorctl restart all